# Schema for configuration files of the ImageAPI Optimize module.

imageapi_optimize.processor.kraken:
  type: mapping
  mapping:
    api_key:
      label: 'API Key'
      type: string
    api_secret:
      label: 'API Secret'
      type: string
    lossy:
      label: 'Enable lossy compression'
      type: boolean
